# Generated by Django 5.2.3 on 2025-06-25 13:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="school",
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
